name: MOVIMENTO
favicon: null
layout_spectrum: 0.6122760269790888
typography_spectrum: 0.5727470791898668
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6462625844869763
  lightness: 0.1441066220868379
  saturation: 0.37299485923722386
  rhythmicContrast: 0.9743390923831612
purpose: []
